### ISSUE TITLE
Projectiles without shooter cause a NullPointerException

### ISSUE THREAD

**Issue by opl-** [MCME/MCME-Entities#4]
```java
player.world.spawn(player.location, Firework.class);
```

Above code causes the following exception to be thrown:

<pre>
[17:25:40 ERROR]: Could not pass event ProjectileLaunchEvent to MCME-Entities v1.0
java.lang.NullPointerException: Cannot invoke "com.mcmiddleearth.entities.entities.McmeEntity.getEntityId()" because "shooter" is null
	at com.mcmiddleearth.entities.protocol.packets.simple.ProjectileSpawnPacket.<init>(ProjectileSpawnPacket.java:24) ~[MCME-Entities-1.0.jar:?]
	at com.mcmiddleearth.entities.entities.Projectile.<init>(Projectile.java:45) ~[MCME-Entities-1.0.jar:?]
	at com.mcmiddleearth.entities.api.VirtualEntityFactory.build(VirtualEntityFactory.java:572) ~[MCME-Entities-1.0.jar:?]
	at com.mcmiddleearth.entities.server.SyncEntityServer.spawnEntity(SyncEntityServer.java:145) ~[MCME-Entities-1.0.jar:?]
	at com.mcmiddleearth.entities.events.listener.ProjectileListener.onProjectileLaunch(ProjectileListener.java:49) ~[MCME-Entities-1.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-317]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1398) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:649) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1422) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1331) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.addEntityToWorld(CraftWorld.java:1063) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftRegionAccessor.addEntity(CraftRegionAccessor.java:523) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftRegionAccessor.spawn(CraftRegionAccessor.java:499) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftRegionAccessor.spawn(CraftRegionAccessor.java:493) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftRegionAccessor.spawn(CraftRegionAccessor.java:484) ~[paper-1.18.2.jar:git-Paper-317]
        [snip]
</pre>

**Comment by EriolEandur** [comment]
I commited a fix to development branch that uses a default entity id (10000) if there is no shooter. 
I guess this should work but can't run any test right now.
